# Generated by Django 5.0.7 on 2024-08-08 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateRole',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('roleName', models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('MEMBER', 'Member')], default='MEMBER', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('userName', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.createrole')),
            ],
        ),
    ]
