# Generated by Django 5.0.7 on 2024-08-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_address_user_dateofbirth_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('DO', 'Done'), ('IN', 'In Progress'), ('DE', 'Delay')], max_length=20, null=True),
        ),
    ]
