# Generated by Django 5.0.7 on 2024-08-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='createrole',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
