# Generated by Django 5.0.7 on 2024-08-13 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_employee_id_user_createddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('serviceRequest_id', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(blank=True, max_length=22)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(blank=True, choices=[('DO', 'Done'), ('IN', 'In Progress'), ('DE', 'Delay')], max_length=20, null=True)),
                ('numberOfGuards', models.IntegerField(default=5)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('note', models.CharField(max_length=250)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('updatedDate', models.DateField()),
                ('deletedAt', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('serviceName', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('DO', 'Done'), ('IN', 'In Progress'), ('DE', 'Delay')], max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('servicerequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.servicerequest')),
                ('contract_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paymethod', models.CharField(blank=True, choices=[('CA', 'Cash'), ('BA', 'Bank')], max_length=4)),
                ('rating', models.IntegerField(blank=True, choices=[(5, 'VeryGood'), (4, 'Good'), (3, 'Normal'), (2, 'Bad'), (1, 'VeryBad')])),
                ('feedback', models.CharField(max_length=255)),
            ],
            bases=('api.servicerequest',),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service'),
        ),
    ]
