# Generated by Django 5.0.7 on 2024-08-15 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_servicerequest_service_alter_user_status_contract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.employee')),
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('link_profile', models.CharField(max_length=255)),
            ],
            bases=('api.employee',),
        ),
        migrations.RenameField(
            model_name='createrole',
            old_name='roleName',
            new_name='role_name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='serviceName',
            new_name='service_name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='updatedDate',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='deletedAt',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='numberOfGuards',
            new_name='number_of_guards',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='serviceRequest_id',
            new_name='service_request_id',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='updatedDate',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dateOfBirth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='deletedAt',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updatedDate',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=22),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.contract')),
                ('mission_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('task_description', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            bases=('api.contract',),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('informaition', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('file_link_report', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contract')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
