# Generated by Django 5.0.7 on 2024-08-20 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_rename_rolename_createrole_role_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('mission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.mission')),
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkin_time', models.DateTimeField()),
                ('checkout_time', models.DateTimeField()),
                ('date', models.DateField()),
            ],
            bases=('api.mission',),
        ),
        migrations.CreateModel(
            name='ClassTraining',
            fields=[
                ('class_training_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_class_training', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('descritption', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deleted_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCatalog',
            fields=[
                ('training_catalog_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_catalog_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('certificate', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Training',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.employee')),
                ('employee_training_id', models.AutoField(primary_key=True, serialize=False)),
                ('assess', models.CharField(max_length=255)),
                ('class_training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classtraining')),
            ],
            bases=('api.employee',),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_file', models.CharField(max_length=255)),
                ('linkFile', models.CharField(max_length=255)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.user')),
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('titile', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            bases=('api.user',),
        ),
        migrations.AddField(
            model_name='classtraining',
            name='training_catalog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trainingcatalog'),
        ),
    ]
